name: Hydra authz testing Conftest

permissions:
  contents: read
  pull-requests: write
  security-events: write
  actions: read
 
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  hydra-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Conftest
        run: |
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.68.2/conftest_0.68.2_Linux_x86_64.tar.gz
          echo "e8144c6d6d2ae0260b869caa60c7c262a1f95ac63ec1e5d2fb19be452d606347  conftest.tar.gz" | sha256sum -c
          tar xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/
     
      - name: Get changed yaml files
        id: changed-files-yaml
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files: |
            **/*.yml
            **/*.yaml
          files_ignore: |
            .github/**

      - name: Run Conftest
        id: conftest
        if: steps.changed-files-yaml.outputs.any_changed == 'true'
        run: conftest test --output sarif ${{ steps.changed-files-yaml.outputs.all_changed_files }} | tee results.sarif
        continue-on-error: true

      - name: Filter SARIF
        if: steps.changed-files-yaml.outputs.any_changed == 'true'
        uses: advanced-security/filter-sarif@2da736ff05ef065cb2894ac6892e47b5eac2c3c0 # v1.1
        with:
          severity: HIGH
          input: results.sarif
          output: results.sarif

      - name: Upload Conftest scan SARIF report
        if: steps.changed-files-yaml.outputs.any_changed == 'true'
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: results.sarif

      - name: Fail if Conftest found violations
        if: steps.conftest.outcome == 'failure'
        run: exit 1
